name: my-contacts

services:
  postgres:
    image: bitnami/postgresql:16
    container_name: my-contacts-postgres
    restart: always
    environment:
      - POSTGRESQL_USERNAME=my_contacts
      - POSTGRESQL_PASSWORD=my_contacts
      - POSTGRESQL_DATABASE=my_contacts_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/bitnami/postgresql
      - ./schemas.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: bitnami/redis:latest
    container_name: my-contacts-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  postgres-data:
  redis-data:
